env: flex
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
    release_app: discord_splatoon_bot
beta_settings:
    cloud_sql_instances: discordsplatoonbot:us-central1:discordsplatoonbot-rdb
automatic_scaling:
    max_num_instances: 1
